version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YAHYA1337
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:YAHYA1337@db:5432/mydb"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    entrypoint:
      [
        "sh",
        "-c",
        "npx prisma db push && npm run build && npm run start",
      ]

networks:
  app-network:
